import { useState } from "react";
import { History, RotateCcw, Download, FileJson, Upload, Image as ImageIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { getLocalizationConfig } from "@/data/localization";

export type HistoryProject = { _id: string; fileName: string; status: string; pageCount: number; wordCount: number; createdAt: number; zipUrl?: string; translationMode?: string };

export function HistoryPanel({ projects, onOpen, onResume, onExport, onImport, onImage }: { projects: HistoryProject[]; onOpen: (project: HistoryProject) => void; onResume: (project: HistoryProject) => void; onExport: (project: HistoryProject) => void; onImport: (file: File) => void; onImage: (file: File, langCode: string) => void }) {
  const [expanded, setExpanded] = useState(false);
  return <section className="rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><History className="size-4 text-violet-300" /><h2 className="font-semibold">Your translations</h2></div><div className="flex gap-2"><label className="btn-royal-hover inline-flex cursor-pointer items-center gap-2 rounded-md border border-white/15 px-3 py-2 text-xs text-muted-foreground hover:text-foreground"><Upload size={14} />Import JSON<input type="file" accept="application/json" className="hidden" onChange={(e) => e.target.files?.[0] && onImport(e.target.files[0])} /></label></div></div>{projects.length === 0 ? <p className="mt-4 text-sm text-muted-foreground">Your completed and in-progress projects will appear here.</p> : <div className="mt-4 space-y-2">{projects.slice(0, expanded ? projects.length : 3).map((project) => <div key={project._id} className="rounded-xl border border-white/10 bg-white/[.02] p-3"><div className="flex flex-wrap items-center gap-3"><button className="min-w-0 flex-1 text-left" onClick={() => onOpen(project)}><p className="truncate text-sm font-semibold">{project.fileName}</p><p className="text-xs text-muted-foreground">{project.pageCount} pages · {project.wordCount.toLocaleString()} words · {new Date(project.createdAt).toLocaleDateString()}</p></button><Badge variant="outline" className="border-violet-300/25 text-violet-200">{project.status}</Badge><Button size="sm" variant="ghost" onClick={() => onResume(project)}><RotateCcw />Resume</Button>{project.zipUrl && <Button size="sm" variant="ghost" onClick={() => onExport(project)}><Download />ZIP</Button>}<Button size="sm" variant="ghost" onClick={() => onExport(project)}><FileJson />JSON</Button></div></div>)}{projects.length > 3 && <button className="w-full py-2 text-xs text-cyan-200" onClick={() => setExpanded(!expanded)}>{expanded ? "Show less" : `Show ${projects.length - 3} more`}</button>}</div>}</section>;
}

export function ImageTranslator({ onTranslate }: { onTranslate: (file: File, langCode: string) => void }) {
  const [langCode, setLangCode] = useState("fr");
  return <div className="rounded-xl border border-violet-300/15 bg-violet-950/10 p-4"><div className="flex items-center gap-2"><ImageIcon className="size-4 text-violet-300" /><h3 className="font-semibold">Image / camera</h3></div><p className="mt-1 text-xs text-muted-foreground">OCR and translate one image without touching your project.</p><div className="mt-3 flex flex-wrap gap-2"><select className="rounded-md border border-white/15 bg-[#10162a] px-3 py-2 text-sm" value={langCode} onChange={(e) => setLangCode(e.target.value)}>{Object.entries({ fr: "Français", ar: "العربية", es: "Español", ja: "日本語", de: "Deutsch" }).map(([code, name]) => <option key={code} value={code}>{name}</option>)}</select><label className="inline-flex cursor-pointer items-center gap-2 rounded-md bg-violet-500 px-3 py-2 text-sm font-semibold text-white hover:bg-violet-400"><ImageIcon size={15} />Choose image<input type="file" accept="image/*" capture="environment" className="hidden" onChange={(e) => e.target.files?.[0] && onTranslate(e.target.files[0], langCode)} /></label></div></div>;
}
